"""remove age add alcohol to guest_group_members

Revision ID: 1e66b4ed38cd
Revises: 5b9f914748f0
Create Date: 2026-03-29 12:36:11.109938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e66b4ed38cd'
down_revision: Union[str, Sequence[str], None] = '5b9f914748f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add alcohol column with default False first (to handle existing rows)
    with op.batch_alter_table('guest_group_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alcohol', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # Migrate: if age >= 21 then alcohol = true
    op.execute("UPDATE guest_group_members SET alcohol = 1 WHERE age >= 21")

    # Now drop the age column
    with op.batch_alter_table('guest_group_members', schema=None) as batch_op:
        batch_op.drop_column('age')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_group_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=True))
        batch_op.drop_column('alcohol')

    # ### end Alembic commands ###
